<?php

namespace DoctrineProxies\__CG__\LabManager\Bean;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Membro extends \LabManager\Bean\Membro implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'id', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'laboratorio', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'nome', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'ativo', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'tipo', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'email', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'telefone', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'facebook', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'twitter', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'linkdl', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'data_entrada', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'data_saida', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'biografia', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'area_interesse', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'admin', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'senha', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'lattes', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'foto', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'chefeProjeto', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'membro_projeto');
        }

        return array('__isInitialized__', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'id', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'laboratorio', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'nome', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'ativo', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'tipo', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'email', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'telefone', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'facebook', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'twitter', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'linkdl', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'data_entrada', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'data_saida', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'biografia', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'area_interesse', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'admin', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'senha', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'lattes', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'foto', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'chefeProjeto', '' . "\0" . 'LabManager\\Bean\\Membro' . "\0" . 'membro_projeto');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Membro $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getLaboratorio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLaboratorio', array());

        return parent::getLaboratorio();
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function getAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtivo', array());

        return parent::getAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', array());

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefone', array());

        return parent::getTelefone();
    }

    /**
     * {@inheritDoc}
     */
    public function getFacebook()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacebook', array());

        return parent::getFacebook();
    }

    /**
     * {@inheritDoc}
     */
    public function getTwitter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTwitter', array());

        return parent::getTwitter();
    }

    /**
     * {@inheritDoc}
     */
    public function getLinkdl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLinkdl', array());

        return parent::getLinkdl();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_entrada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_entrada', array());

        return parent::getData_entrada();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_saida()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_saida', array());

        return parent::getData_saida();
    }

    /**
     * {@inheritDoc}
     */
    public function getBiografia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBiografia', array());

        return parent::getBiografia();
    }

    /**
     * {@inheritDoc}
     */
    public function getArea_interesse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArea_interesse', array());

        return parent::getArea_interesse();
    }

    /**
     * {@inheritDoc}
     */
    public function getAdmin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdmin', array());

        return parent::getAdmin();
    }

    /**
     * {@inheritDoc}
     */
    public function getSenha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenha', array());

        return parent::getSenha();
    }

    /**
     * {@inheritDoc}
     */
    public function getLattes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLattes', array());

        return parent::getLattes();
    }

    /**
     * {@inheritDoc}
     */
    public function getFoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFoto', array());

        return parent::getFoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setLaboratorio($laboratorio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLaboratorio', array($laboratorio));

        return parent::setLaboratorio($laboratorio);
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', array($nome));

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function setAtivo($ativo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtivo', array($ativo));

        return parent::setAtivo($ativo);
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', array($tipo));

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefone($telefone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefone', array($telefone));

        return parent::setTelefone($telefone);
    }

    /**
     * {@inheritDoc}
     */
    public function setFacebook($facebook)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacebook', array($facebook));

        return parent::setFacebook($facebook);
    }

    /**
     * {@inheritDoc}
     */
    public function setTwitter($twitter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTwitter', array($twitter));

        return parent::setTwitter($twitter);
    }

    /**
     * {@inheritDoc}
     */
    public function setLinkdl($linkdl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLinkdl', array($linkdl));

        return parent::setLinkdl($linkdl);
    }

    /**
     * {@inheritDoc}
     */
    public function setData_entrada($data_entrada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData_entrada', array($data_entrada));

        return parent::setData_entrada($data_entrada);
    }

    /**
     * {@inheritDoc}
     */
    public function setData_saida($data_saida)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData_saida', array($data_saida));

        return parent::setData_saida($data_saida);
    }

    /**
     * {@inheritDoc}
     */
    public function setBiografia($biografia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBiografia', array($biografia));

        return parent::setBiografia($biografia);
    }

    /**
     * {@inheritDoc}
     */
    public function setArea_interesse($area_interesse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArea_interesse', array($area_interesse));

        return parent::setArea_interesse($area_interesse);
    }

    /**
     * {@inheritDoc}
     */
    public function setAdmin($admin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdmin', array($admin));

        return parent::setAdmin($admin);
    }

    /**
     * {@inheritDoc}
     */
    public function setSenha($senha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenha', array($senha));

        return parent::setSenha($senha);
    }

    /**
     * {@inheritDoc}
     */
    public function setLattes($lattes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLattes', array($lattes));

        return parent::setLattes($lattes);
    }

    /**
     * {@inheritDoc}
     */
    public function setFoto($foto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFoto', array($foto));

        return parent::setFoto($foto);
    }

    /**
     * {@inheritDoc}
     */
    public function getChefeProjeto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChefeProjeto', array());

        return parent::getChefeProjeto();
    }

    /**
     * {@inheritDoc}
     */
    public function setChefeProjeto(\LabManager\Bean\Projeto $chefeProjeto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChefeProjeto', array($chefeProjeto));

        return parent::setChefeProjeto($chefeProjeto);
    }

    /**
     * {@inheritDoc}
     */
    public function getMembroProjeto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMembroProjeto', array());

        return parent::getMembroProjeto();
    }

    /**
     * {@inheritDoc}
     */
    public function setMembroProjeto(\LabManager\Bean\MembroProjeto $membro_projeto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMembroProjeto', array($membro_projeto));

        return parent::setMembroProjeto($membro_projeto);
    }

}
